const mongoose = require("mongoose"); const { connectDatabase, disconnectDatabase } = require("../src/config/database"); const slugify = require("../src/utils/slug"); const Agent = require("../src/modules/agents/agent.model"); const Agency = require("../src/modules/agents/agency.model"); const Property = require("../src/modules/properties/property.model"); const Booking = require("../src/modules/bookings/booking.model");
const dryRun = !process.argv.includes("--apply");
const purpose = (value) => value === "shortStay" ? "short_stay" : value;
const type = (value) => ({ villa: "house", studio: "apartment" }[value] || value || "other");
async function unique(Model, base) { let slug = base || "record", n = 2; while (await Model.exists({ slug })) slug = `${base}-${n++}`; return slug; }
async function run() { await connectDatabase(); const legacyProperties = mongoose.connection.collection("properties"); const docs = await legacyProperties.find({ slug: { $exists: false } }).toArray(); let changed = 0; for (const doc of docs) { const oldAgent = doc.agent || {}; let agency; let agent; if (oldAgent.company) { const agencySlug = slugify(oldAgent.company); agency = await Agency.findOne({ slug: agencySlug }); if (!agency && !dryRun) agency = await Agency.create({ name: oldAgent.company, slug: await unique(Agency, agencySlug), phone: oldAgent.phone, email: oldAgent.email }); } if (oldAgent.name && !dryRun) { agent = await Agent.findOne({ email: oldAgent.email?.toLowerCase() }); if (!agent) agent = await Agent.create({ name: oldAgent.name, slug: await unique(Agent, slugify(oldAgent.name)), agency: agency?.id, phone: oldAgent.phone, email: oldAgent.email, photo: oldAgent.photo }); }
    const media = [...(doc.images || []).map((url) => ({ url, type: "image" })), ...(doc.videos || []).map((url) => ({ url, type: "video" }))]; const replacement = { slug: await unique(Property, slugify(doc.title)), purpose: purpose(doc.purpose), type: type(doc.type), price: { amount: doc.price || 0, currency: "UGX", period: doc.purpose === "rent" ? "month" : doc.purpose === "shortStay" ? "night" : "total" }, location: { country: "Uganda", region: doc.region || "", district: doc.district || "", area: doc.area || "", address: doc.location || "" }, bedrooms: doc.size?.bedrooms, bathrooms: doc.size?.bathrooms, size: doc.size?.totalArea, sizeUnit: "sqm", media, cover: media.find((item) => item.type === "image"), agent: agent?.id, agency: agency?.id, legacyAgent: oldAgent, featured: Boolean(doc.isFeatured), verificationStatus: "unverified", status: doc.isActive === false ? "archived" : "published", publishedAt: doc.datePosted || doc.createdAt || new Date(), viewCount: doc.views || 0 };
    if (!dryRun) await legacyProperties.updateOne({ _id: doc._id }, { $set: replacement, $unset: { images: "", videos: "", isFeatured: "", isActive: "", datePosted: "", views: "", favorites: "", rating: "", reviewCount: "" } }); changed++; }
  const appointments = await mongoose.connection.collection("appointments").find({ migratedToBooking: { $ne: true } }).toArray(); for (const item of appointments) if (!dryRun && item.propertyId && item.appointmentTime) { await Booking.create({ reference: `HOM-LEGACY-${String(item._id).slice(-8).toUpperCase()}`, property: item.propertyId, guestName: item.name, guestEmail: item.email, guestPhone: item.phone, scheduledAt: item.appointmentTime, duration: parseInt(item.duration, 10) || 60, notes: item.notes, status: "pending" }); await mongoose.connection.collection("appointments").updateOne({ _id: item._id }, { $set: { migratedToBooking: true } }); }
  process.stdout.write(`${dryRun ? "Dry run" : "Migration"}: ${changed} properties and ${appointments.length} appointments identified.\n`); await disconnectDatabase(); }
run().catch(async (error) => { process.stderr.write(`${error.stack}\n`); await disconnectDatabase().catch(() => {}); process.exit(1); });
